Improve checks on commands, make initial_config() more robust, and improve usage printout
- commands that affect virtualenvs now make sure the specified virtualenv exists before running
- initial_config takes care of copying revenv to PATH if needed
- more detailed help in usage

diff --git a/revenv b/revenv
--- a/revenv
+++ b/revenv
@@ -18,8 +18,8 @@ launch_zshell() {
     for zfile in "$HOME"/.z*; do
         cp "$zfile" "$ZDOTDIR"
     done
-    echo 'export PS1="%{$fg_bold[blue]%}($(basename "$VIRTUAL_ENV")) $PS1"' 2>/dev/null >> "$ZDOTDIR/.zshrc"    
-    echo 'export PS1="%{$fg_bold[blue]%}($(basename "$VIRTUAL_ENV")) $PS1"' 2>/dev/null >> "$ZDOTDIR/.zprofile" 
+    echo 'export PS1="%{$fg_bold[blue]%}($(basename "$VIRTUAL_ENV")) $PS1"' 2>/dev/null >> "$ZDOTDIR/.zshrc"
+    echo 'export PS1="%{$fg_bold[blue]%}($(basename "$VIRTUAL_ENV")) $PS1"' 2>/dev/null >> "$ZDOTDIR/.zprofile"
     export ZDOTDIR
     zsh
     rm -rf "$ZDOTDIR"
@@ -45,6 +45,7 @@ launch_shell() {
 
 start_venv() {
     export VIRTUAL_ENV="$WORKON_HOME/$1"
+    check_venv_exists "$1" || exit 1
     export PATH="$VIRTUAL_ENV/bin:$PATH"
     unset PYTHON_HOME
     echo "Starting revenv at [$VIRTUAL_ENV]"
@@ -59,16 +60,26 @@ new_venv() {
 }
 
 del_venv() {
+    check_venv_exists "$1" || exit 1
     local target="$WORKON_HOME/$1"
     local choice
     read -p "About to delete venv at: ${target}. Sure (y/n)? " choice
-    case "$choice" in 
+    case "$choice" in
         y|yes|Y)
-            rm -rf "$target" && 
+            rm -rf "$target" &&
             echo "Deleted venv at [$target]" ||
                 echo "Unable to delete virtualenv at $target"
             ;;
     esac
+}
+
+check_venv_exists() {
+    # Check if a venv exists, die if not present
+    if [[ ! -d "$WORKON_HOME/$1" ]]; then
+        echo "Virtualenv '$1' not found! You can create a new virtualenv with "\
+            "\`$(basename $0) new [VENV_NAME]\`"
+        return 1
+    fi
 }
 
 initial_config() {
@@ -77,48 +88,92 @@ initial_config() {
     [[ -z $storage_dir ]] && storage_dir="$default_storage_dir"
     echo "export WORKON_HOME=\"$storage_dir\"" > "$HOME/.revenv"
     export WORKON_HOME="$storage_dir"
+    mkdir -p "$WORKON_HOME" &> /dev/null
+
+    if ! which $(basename $0) &> /dev/null; then
+        read -p "$(basename $0) not found in PATH. Copy to /usr/local/bin/$(basename $0)? (y/n) [y] " choice
+        case "$choice" in
+            y|Y|yes)
+                cp "$0" "/usr/local/bin/$(basename $0)" || (
+                    echo "Copy failed, retrying with sudo (please enter sudo pw if prompted)"
+                    sudo cp "$0" "/usr/local/bin/$(basename $0)"
+                )
+                ;;
+        esac
+    fi
+
 }
 
 ls_venvs() {
     local startdir="$PWD"
     cd "$WORKON_HOME"
+    echo "Virtualenvs in [$WORKON_HOME]:"
     ls
     cd "$startdir"
 }
 
 usage() {
     local exename=$(basename $0)
-    local usage="$exename provides a simple wrapper around virtualenv to let you work on your\nvirtualenvs in one place. Functionality is intentionally quite minimal.\n\nUsage: \n    $exename [ setup | workon | ls | new | rm ]\n"
-    echo -e "$usage"
+cat <<- _EOF_
+$exename provides a simple wrapper around virtualenv to let you work on your
+virtualenvs in one place. Functionality is intentionally quite minimal.
+
+Usage:
+    $exename [ setup | workon | ls | new | rm ]
+
+setup
+    Initial config of revenv. Will set a WORKON_HOME (the directory where
+    your virtualenvs will live) if one doesn't exist.
+
+workon [virtualenv name]
+    Activate the specified virtualenv
+
+ls
+    List all virtualenvs in the \$WORKON_HOME directory
+
+new [virtualenv name]
+    Create a new virtualenv with the specified name
+
+rm [virtualenv name]
+    Deletes specified virtualenv
+
+_EOF_
 }
 
 check_deps() {
-    if [[ -z $WORKON_HOME ]]; then
-        read -p "No WORKON_HOME environment variable found. Run initial config? (y/n) " choice
-        case "$choice" in 
+    if [[ ! -d $WORKON_HOME ]]; then
+        read -p "No WORKON_HOME found. Run initial config? (y/n) " choice
+        case "$choice" in
             y|Y|yes)
                 initial_config
                 ;;
         esac
     fi
 
-    if ! which virtualenv > /dev/null 2>&1; then
-        echo "$(basename $0) relies on virtualenv -- you can install it with this command: pip install virtualenv"
-        exit 1
+    if ! which pip &> /dev/null ; then
+        echo -e "You don't seem to have pip installed. Please install pip (on most systems you can do this via \`easy_install pip\`) and run $(basename $0) again.\n"
+        failed=true
     fi
+
+    if ! which virtualenv &> /dev/null ; then
+        echo -e "You don't seem to have virtualenv installed. Please install virtualenv via \`pip install virtualenv\` and run $(basename $0) again."
+        failed=true
+    fi
+
+    [[ -n $failed ]] && exit 1
 }
 
 
 
 if [[ -f "$HOME/.revenv" ]]; then
-    source "$HOME/.revenv" 
+    source "$HOME/.revenv"
 fi
 
 check_deps
 
 
 case "$1" in
-    init|setup|initial-setup)
+    initial-config|init|setup|initial-setup)
         initial_config
         ;;
     w|workon|work_on|work-on)
@@ -129,7 +184,7 @@ case "$1" in
         shift
         new_venv $*
         ;;
-    rm) 
+    rm)
         shift
         del_venv $*
         ;;
